spring.application.name=psicon-api
server.port=${PORT:8080}


spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/psicon_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


app.jwt.secret=${JWT_SECRET:psicon_jwt_secret_key_2025_muy_segura}
app.jwt.expiration=86400000