spring.application.name=psicon-api
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://postgres:QEAzYzCeFCPVApUIJcNmqnDzBkiwIjvi@thomas.proxy.rlwy.net:51437/railway
spring.datasource.username=postgres
spring.datasource.password=QEAzYzCeFCPVApUIJcNmqnDzBkiwIjvi
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=psicon_jwt_secret_key_2025_muy_segura
app.jwt.expiration=86400000